INSERT INTO genders(id, gender, created_at, updated_at)
VALUES (1, 'Male', now(), now()),
       (2, 'Female', now(), now()),
       (3, 'NonBinary', now(), now()),
       (4, 'Other', now(), now()),
       (5, 'PreferNotToSay', now(), now());

insert into countries(id, created_at, updated_at, country_name, country_iso_code)
values (1, now(), now(), 'Afghanistan', 'AFG'),
       (2, now(), now(), 'Albania', 'ALB'),
       (3, now(), now(), 'Algeria', 'DZA'),
       (4, now(), now(), 'American Samoa', 'ASM'),
       (5, now(), now(), 'Andorra', 'AND'),
       (6, now(), now(), 'Angola', 'AGO'),
       (7, now(), now(), 'Anguilla', 'AIA'),
       (8, now(), now(), 'Antarctica', 'ATA'),
       (9, now(), now(), 'Antigua and Barbuda', 'ATG'),
       (10, now(), now(), 'Argentina', 'ARG'),
       (11, now(), now(), 'Armenia', 'ARM'),
       (12, now(), now(), 'Aruba', 'ABW'),
       (13, now(), now(), 'Australia', 'AUS'),
       (14, now(), now(), 'Austria', 'AUT'),
       (15, now(), now(), 'Azerbaijan', 'AZE'),
       (16, now(), now(), 'Bahamas', 'BHS'),
       (17, now(), now(), 'Bahrain', 'BHR'),
       (18, now(), now(), 'Bangladesh', 'BGD'),
       (19, now(), now(), 'Barbados', 'BRB'),
       (20, now(), now(), 'Belarus', 'BLR'),
       (21, now(), now(), 'Belgium', 'BEL'),
       (22, now(), now(), 'Belize', 'BLZ'),
       (23, now(), now(), 'Benin', 'BEN'),
       (24, now(), now(), 'Bermuda', 'BMU'),
       (25, now(), now(), 'Bhutan', 'BTN'),
       (26, now(), now(), 'Bolivia', 'BOL'),
       (27, now(), now(), 'Bosnia and Herzegovina', 'BIH'),
       (28, now(), now(), 'Botswana', 'BWA'),
       (29, now(), now(), 'Brazil', 'BRA'),
       (30, now(), now(), 'British Indian Ocean Territory', 'IOT'),
       (31, now(), now(), 'British Virgin Islands', 'VGB'),
       (32, now(), now(), 'Brunei', 'BRN'),
       (33, now(), now(), 'Bulgaria', 'BGR'),
       (34, now(), now(), 'Burkina Faso', 'BFA'),
       (35, now(), now(), 'Myanmar', 'MMR'),
       (36, now(), now(), 'Burundi', 'BDI'),
       (37, now(), now(), 'Cambodia', 'KHM'),
       (38, now(), now(), 'Cameroon', 'CMR'),
       (39, now(), now(), 'Canada', 'CAN'),
       (40, now(), now(), 'Cape Verde', 'CPV'),
       (41, now(), now(), 'Cayman Islands', 'CYM'),
       (42, now(), now(), 'Central African Republic', 'CAF'),
       (43, now(), now(), 'Chad', 'TCD'),
       (44, now(), now(), 'Chile', 'CHL'),
       (45, now(), now(), 'China', 'CHN'),
       (46, now(), now(), 'Christmas Island', 'CXR'),
       (47, now(), now(), 'Cocos Islands', 'CCK'),
       (48, now(), now(), 'Colombia', 'COL'),
       (49, now(), now(), 'Comoros', 'COM'),
       (50, now(), now(), 'Republic of the Congo', 'COG'),
       (51, now(), now(), 'Democratic Republic of the Congo', 'COD'),
       (52, now(), now(), 'Cook Islands', 'COK'),
       (53, now(), now(), 'Costa Rica', 'CRI'),
       (54, now(), now(), 'Croatia', 'HRV'),
       (55, now(), now(), 'Cuba', 'CUB'),
       (56, now(), now(), 'Curacao', 'CUW'),
       (57, now(), now(), 'Cyprus', 'CYP'),
       (58, now(), now(), 'Czech Republic', 'CZE'),
       (59, now(), now(), 'Denmark', 'DNK'),
       (60, now(), now(), 'Djibouti', 'DJI'),
       (61, now(), now(), 'Dominica', 'DMA'),
       (62, now(), now(), 'Dominican Republic', 'DOM'),
       (63, now(), now(), 'East Timor', 'TLS'),
       (64, now(), now(), 'Ecuador', 'ECU'),
       (65, now(), now(), 'Egypt', 'EGY'),
       (66, now(), now(), 'El Salvador', 'SLV'),
       (67, now(), now(), 'Equatorial Guinea', 'GNQ'),
       (68, now(), now(), 'Eritrea', 'ERI'),
       (69, now(), now(), 'Estonia', 'EST'),
       (70, now(), now(), 'Ethiopia', 'ETH'),
       (71, now(), now(), 'Falkland Islands', 'FLK'),
       (72, now(), now(), 'Faroe Islands', 'FRO'),
       (73, now(), now(), 'Fiji', 'FJI'),
       (74, now(), now(), 'Finland', 'FIN'),
       (75, now(), now(), 'France', 'FRA'),
       (76, now(), now(), 'French Polynesia', 'PYF'),
       (77, now(), now(), 'Gabon', 'GAB'),
       (78, now(), now(), 'Gambia', 'GMB'),
       (79, now(), now(), 'Georgia', 'GEO'),
       (80, now(), now(), 'Germany', 'DEU'),
       (81, now(), now(), 'Ghana', 'GHA'),
       (82, now(), now(), 'Gibraltar', 'GIB'),
       (83, now(), now(), 'Greece', 'GRC'),
       (84, now(), now(), 'Greenland', 'GRL'),
       (85, now(), now(), 'Grenada', 'GRD'),
       (86, now(), now(), 'Guam', 'GUM'),
       (87, now(), now(), 'Guatemala', 'GTM'),
       (88, now(), now(), 'Guernsey', 'GGY'),
       (89, now(), now(), 'Guinea', 'GIN'),
       (90, now(), now(), 'Guinea-Bissau', 'GNB'),
       (91, now(), now(), 'Guyana', 'GUY'),
       (92, now(), now(), 'Haiti', 'HTI'),
       (93, now(), now(), 'Honduras', 'HND'),
       (94, now(), now(), 'Hong Kong', 'HKG'),
       (95, now(), now(), 'Hungary', 'HUN'),
       (96, now(), now(), 'Iceland', 'ISL'),
       (97, now(), now(), 'India', 'IND'),
       (98, now(), now(), 'Indonesia', 'IDN'),
       (99, now(), now(), 'Iran', 'IRN'),
       (100, now(), now(), 'Iraq', 'IRQ'),
       (101, now(), now(), 'Ireland', 'IRL'),
       (102, now(), now(), 'Isle of Man', 'IMN'),
       (103, now(), now(), 'Israel', 'ISR'),
       (104, now(), now(), 'Italy', 'ITA'),
       (105, now(), now(), 'Ivory Coast', 'CIV'),
       (106, now(), now(), 'Jamaica', 'JAM'),
       (107, now(), now(), 'Japan', 'JPN'),
       (108, now(), now(), 'Jersey', 'JEY'),
       (109, now(), now(), 'Jordan', 'JOR'),
       (110, now(), now(), 'Kazakhstan', 'KAZ'),
       (111, now(), now(), 'Kenya', 'KEN'),
       (112, now(), now(), 'Kiribati', 'KIR'),
       (113, now(), now(), 'Kosovo', 'XKX'),
       (114, now(), now(), 'Kuwait', 'KWT'),
       (115, now(), now(), 'Kyrgyzstan', 'KGZ'),
       (116, now(), now(), 'Laos', 'LAO'),
       (117, now(), now(), 'Latvia', 'LVA'),
       (118, now(), now(), 'Lebanon', 'LBN'),
       (119, now(), now(), 'Lesotho', 'LSO'),
       (120, now(), now(), 'Liberia', 'LBR'),
       (121, now(), now(), 'Libya', 'LBY'),
       (122, now(), now(), 'Liechtenstein', 'LIE'),
       (123, now(), now(), 'Lithuania', 'LTU'),
       (124, now(), now(), 'Luxembourg', 'LUX'),
       (125, now(), now(), 'Macau', 'MAC'),
       (126, now(), now(), 'Macedonia', 'MKD'),
       (127, now(), now(), 'Madagascar', 'MDG'),
       (128, now(), now(), 'Malawi', 'MWI'),
       (129, now(), now(), 'Malaysia', 'MYS'),
       (130, now(), now(), 'Maldives', 'MDV'),
       (131, now(), now(), 'Mali', 'MLI'),
       (132, now(), now(), 'Malta', 'MLT'),
       (133, now(), now(), 'Marshall Islands', 'MHL'),
       (134, now(), now(), 'Mauritania', 'MRT'),
       (135, now(), now(), 'Mauritius', 'MUS'),
       (136, now(), now(), 'Mayotte', 'MYT'),
       (137, now(), now(), 'Mexico', 'MEX'),
       (138, now(), now(), 'Micronesia', 'FSM'),
       (139, now(), now(), 'Moldova', 'MDA'),
       (140, now(), now(), 'Monaco', 'MCO'),
       (141, now(), now(), 'Mongolia', 'MNG'),
       (142, now(), now(), 'Montenegro', 'MNE'),
       (143, now(), now(), 'Montserrat', 'MSR'),
       (144, now(), now(), 'Morocco', 'MAR'),
       (145, now(), now(), 'Mozambique', 'MOZ'),
       (146, now(), now(), 'Namibia', 'NAM'),
       (147, now(), now(), 'Nauru', 'NRU'),
       (148, now(), now(), 'Nepal', 'NPL'),
       (149, now(), now(), 'Netherlands', 'NLD'),
       (150, now(), now(), 'Netherlands Antilles', 'ANT'),
       (151, now(), now(), 'New Caledonia', 'NCL'),
       (152, now(), now(), 'New Zealand', 'NZL'),
       (153, now(), now(), 'Nicaragua', 'NIC'),
       (154, now(), now(), 'Niger', 'NER'),
       (155, now(), now(), 'Nigeria', 'NGA'),
       (156, now(), now(), 'Niue', 'NIU'),
       (157, now(), now(), 'Northern Mariana Islands', 'MNP'),
       (158, now(), now(), 'North Korea', 'PRK'),
       (159, now(), now(), 'Norway', 'NOR'),
       (160, now(), now(), 'Oman', 'OMN'),
       (161, now(), now(), 'Pakistan', 'PAK'),
       (162, now(), now(), 'Palau', 'PLW'),
       (163, now(), now(), 'Palestine', 'PSE'),
       (164, now(), now(), 'Panama', 'PAN'),
       (165, now(), now(), 'Papua New Guinea', 'PNG'),
       (166, now(), now(), 'Paraguay', 'PRY'),
       (167, now(), now(), 'Peru', 'PER'),
       (168, now(), now(), 'Philippines', 'PHL'),
       (169, now(), now(), 'Pitcairn', 'PCN'),
       (170, now(), now(), 'Poland', 'POL'),
       (171, now(), now(), 'Portugal', 'PRT'),
       (172, now(), now(), 'Puerto Rico', 'PRI'),
       (173, now(), now(), 'Qatar', 'QAT'),
       (174, now(), now(), 'Reunion', 'REU'),
       (175, now(), now(), 'Romania', 'ROU'),
       (176, now(), now(), 'Russia', 'RUS'),
       (177, now(), now(), 'Rwanda', 'RWA'),
       (178, now(), now(), 'Saint Barthelemy', 'BLM'),
       (179, now(), now(), 'Samoa', 'WSM'),
       (180, now(), now(), 'San Marino', 'SMR'),
       (181, now(), now(), 'Sao Tome and Principe', 'STP'),
       (182, now(), now(), 'Saudi Arabia', 'SAU'),
       (183, now(), now(), 'Senegal', 'SEN'),
       (184, now(), now(), 'Serbia', 'SRB'),
       (185, now(), now(), 'Seychelles', 'SYC'),
       (186, now(), now(), 'Sierra Leone', 'SLE'),
       (187, now(), now(), 'Singapore', 'SGP'),
       (188, now(), now(), 'Sint Maarten', 'SXM'),
       (189, now(), now(), 'Slovakia', 'SVK'),
       (190, now(), now(), 'Slovenia', 'SVN'),
       (191, now(), now(), 'Solomon Islands', 'SLB'),
       (192, now(), now(), 'Somalia', 'SOM'),
       (193, now(), now(), 'South Africa', 'ZAF'),
       (194, now(), now(), 'South Korea', 'KOR'),
       (195, now(), now(), 'South Sudan', 'SSD'),
       (196, now(), now(), 'Spain', 'ESP'),
       (197, now(), now(), 'Sri Lanka', 'LKA'),
       (198, now(), now(), 'Saint Helena', 'SHN'),
       (199, now(), now(), 'Saint Kitts and Nevis', 'KNA'),
       (200, now(), now(), 'Saint Lucia', 'LCA'),
       (201, now(), now(), 'Saint Martin', 'MAF'),
       (202, now(), now(), 'Saint Pierre and Miquelon', 'SPM'),
       (203, now(), now(), 'Saint Vincent and the Grenadines', 'VCT'),
       (204, now(), now(), 'Sudan', 'SDN'),
       (205, now(), now(), 'Suriname', 'SUR'),
       (206, now(), now(), 'Svalbard and Jan Mayen', 'SJM'),
       (207, now(), now(), 'Swaziland', 'SWZ'),
       (208, now(), now(), 'Sweden', 'SWE'),
       (209, now(), now(), 'Switzerland', 'CHE'),
       (210, now(), now(), 'Syria', 'SYR'),
       (211, now(), now(), 'Taiwan', 'TWN'),
       (212, now(), now(), 'Tajikistan', 'TJK'),
       (213, now(), now(), 'Tanzania', 'TZA'),
       (214, now(), now(), 'Thailand', 'THA'),
       (215, now(), now(), 'Togo', 'TGO'),
       (216, now(), now(), 'Tokelau', 'TKL'),
       (217, now(), now(), 'Tonga', 'TON'),
       (218, now(), now(), 'Trinidad and Tobago', 'TTO'),
       (219, now(), now(), 'Tunisia', 'TUN'),
       (220, now(), now(), 'Turkey', 'TUR'),
       (221, now(), now(), 'Turkmenistan', 'TKM'),
       (222, now(), now(), 'Turks and Caicos Islands', 'TCA'),
       (223, now(), now(), 'Tuvalu', 'TUV'),
       (224, now(), now(), 'United Arab Emirates', 'ARE'),
       (225, now(), now(), 'Uganda', 'UGA'),
       (226, now(), now(), 'United Kingdom', 'GBR'),
       (227, now(), now(), 'Ukraine', 'UKR'),
       (228, now(), now(), 'Uruguay', 'URY'),
       (229, now(), now(), 'United States', 'USA'),
       (230, now(), now(), 'Uzbekistan', 'UZB'),
       (231, now(), now(), 'Vanuatu', 'VUT'),
       (232, now(), now(), 'Vatican', 'VAT'),
       (233, now(), now(), 'Venezuela', 'VEN'),
       (234, now(), now(), 'Vietnam', 'VNM'),
       (235, now(), now(), 'U.S. Virgin Islands', 'VIR'),
       (236, now(), now(), 'Wallis and Futuna', 'WLF'),
       (237, now(), now(), 'Western Sahara', 'ESH'),
       (238, now(), now(), 'Yemen', 'YEM'),
       (239, now(), now(), 'Zambia', 'ZMB'),
       (240, now(), now(), 'Zimbabwe', 'ZWE');

insert into languages(id, created_at, updated_at, language_name, language_code)
values (1,now(),now(),'Mandarin (Chinese)','cmn'),
       (2,now(),now(),'Spanish','spa'),
       (3,now(),now(),'English','eng'),
       (4,now(),now(),'Hindi','hin'),
       (5,now(),now(),'Indonesian','ind'),
       (6,now(),now(),'Arabic','arb'),
       (7,now(),now(),'Bengali','ben'),
       (8,now(),now(),'Portuguese','por'),
       (9,now(),now(),'Russian','rus'),
       (10,now(),now(),'Japanese','jpn'),
       (11,now(),now(),'Panjabi','pan'),
       (12,now(),now(),'German','deu'),
       (13,now(),now(),'Wu (Changzhou)','wuu'),
       (14,now(),now(),'Javanese','jav'),
       (15,now(),now(),'Telugu','tel'),
       (16,now(),now(),'Vietnamese','vie'),
       (17,now(),now(),'Korean','kor'),
       (18,now(),now(),'Marathi','mar'),
       (19,now(),now(),'French','fra'),
       (20,now(),now(),'Tamil','tam'),
       (21,now(),now(),'Urdu','urd'),
       (22,now(),now(),'Turkish','tur'),
       (23,now(),now(),'Cantonese','yue'),
       (24,now(),now(),'Italian','ita'),
       (25,now(),now(),'Thai','tha'),
       (26,now(),now(),'Gujarati','guj'),
       (27,now(),now(),'Min Nan','nan'),
       (28,now(),now(),'Persian (Farsi)','pes'),
       (29,now(),now(),'Polish','pol'),
       (30,now(),now(),'Kannada','kan'),
       (31,now(),now(),'Malay (Melayu)','mly'),
       (32,now(),now(),'Malayalam','mal'),
       (33,now(),now(),'Pashto','pst'),
       (34,now(),now(),'Hausa','hau'),
       (35,now(),now(),'Xiang','hsn'),
       (36,now(),now(),'Sundanese (Sunda)','sun'),
       (37,now(),now(),'Oriya','ori'),
       (38,now(),now(),'Burmese','mya'),
       (39,now(),now(),'Hakka','hak'),
       (40,now(),now(),'Ukrainian','ukr'),
       (41,now(),now(),'Bhojpuri','bho'),
       (42,now(),now(),'Maithili','mai'),
       (43,now(),now(),'Tagalog (Pilipino)','tgl'),
       (44,now(),now(),'Uzbek','uzn'),
       (45,now(),now(),'Yoruba','yor'),
       (46,now(),now(),'Amharic','amh'),
       (47,now(),now(),'Sindhi','snd'),
       (48,now(),now(),'Oromo','gax'),
       (49,now(),now(),'Romanian','ron'),
       (50,now(),now(),'Cebuano','ceb'),
       (51,now(),now(),'Awadhi','awa'),
       (52,now(),now(),'Azerbaijani (Azeri)','azb'),
       (53,now(),now(),'Gan','gan'),
       (54,now(),now(),'Dutch','nld'),
       (55,now(),now(),'Igbo (Ibo)','ibo'),
       (56,now(),now(),'Kurdish (Kurmanji)','kmr'),
       (57,now(),now(),'Serbo-Croatian (*)','bos'),
       (58,now(),now(),'Malagasy','bhr'),
       (59,now(),now(),'Nepali','nep'),
       (60,now(),now(),'Sinhala (Singhalese)','sin'),
       (61,now(),now(),'Seraiki','skr'),
       (62,now(),now(),'Chittagonian','cit'),
       (63,now(),now(),'Zhuang','ccx'),
       (64,now(),now(),'Khmer','khm'),
       (65,now(),now(),'Assamese','asm'),
       (66,now(),now(),'Turkmen','tuk'),
       (67,now(),now(),'Somali','som'),
       (68,now(),now(),'Fulani (Fula, Pulaar, Fulacunda)','fub'),
       (69,now(),now(),'Marwari','rwr'),
       (70,now(),now(),'Madurese (Madura)','mad'),
       (71,now(),now(),'Magahi','mag'),
       (72,now(),now(),'Haryanvi','bgc'),
       (73,now(),now(),'Hungarian (Magyar)','hun'),
       (74,now(),now(),'Chattisgarhi (Laria, Khaltahi)','hne'),
       (75,now(),now(),'Chichewa (Chewa, Nyanja)','nya'),
       (76,now(),now(),'Greek (Modern)','ell'),
       (77,now(),now(),'Deccan','dcc'),
       (78,now(),now(),'Rwanda','kin'),
       (79,now(),now(),'Kazakh','kaz'),
       (80,now(),now(),'Sylheti','syl'),
       (81,now(),now(),'Min Bei','mnp'),
       (82,now(),now(),'Akan','aka'),
       (83,now(),now(),'Zulu','zul'),
       (84,now(),now(),'Serbian (*)','srp'),
       (85,now(),now(),'Czech','ces'),
       (86,now(),now(),'Dhundari','dhd'),
       (87,now(),now(),'Ilocano','ilo'),
       (88,now(),now(),'Min Dong','cdo'),
       (89,now(),now(),'Rundi','run'),
       (90,now(),now(),'Quechua','qxa'),
       (91,now(),now(),'Swedish','swe'),
       (92,now(),now(),'Hiligaynon','hil'),
       (93,now(),now(),'Hmong','hmn'),
       (94,now(),now(),'Shona (Karanga)','sna'),
       (95,now(),now(),'Uyghur','uig'),
       (96,now(),now(),'Balochi (Baluchi)','bgp'),
       (97,now(),now(),'Mooré (Mòoré)','mos'),
       (98,now(),now(),'Konkani','knn'),
       (99,now(),now(),'Xhosa','xho'),
       (100,now(),now(),'Fulfulde','ffm'),
       (101,now(),now(),'CiLuba','lua'),
       (102,now(),now(),'Belarusan (Belorussian)','bel'),
       (103,now(),now(),'Tigrinya Tigrigna','tir'),
       (104,now(),now(),'Bulgarian','bul'),
       (105,now(),now(),'Yi','ycl'),
       (106,now(),now(),'Betawi','bew'),
       (107,now(),now(),'Kikuyu','kik'),
       (108,now(),now(),'Santali','sat'),
       (109,now(),now(),'Dari (E Farsi)','prs'),
       (110,now(),now(),'Mongol(ian)','khk'),
       (111,now(),now(),'Kanauji','bjj'),
       (112,now(),now(),'Albanian','aln'),
       (113,now(),now(),'Catalan','cat'),
       (114,now(),now(),'Afrikaans','afr'),
       (115,now(),now(),'Minangkabau','min'),
       (116,now(),now(),'Croatian (*)','hrv'),
       (117,now(),now(),'Sotho (Southern)','sot'),
       (118,now(),now(),'Wolof','wol'),
       (119,now(),now(),'Kashmiri','kas'),
       (120,now(),now(),'Bikol','bcl'),
       (121,now(),now(),'Mewati','wtm'),
       (122,now(),now(),'Makua (Makhuwa)','vmw'),
       (123,now(),now(),'Swahili','swh'),
       (124,now(),now(),'Danish','dan'),
       (125,now(),now(),'Luganda','lug'),
       (126,now(),now(),'Luyia','luy'),
       (127,now(),now(),'Armenian','hye'),
       (128,now(),now(),'Finnish','fin'),
       (129,now(),now(),'Kanuri','knc'),
       (130,now(),now(),'Bugis','bug'),
       (131,now(),now(),'Tatar','tat'),
       (132,now(),now(),'Tswana','tsn'),
       (133,now(),now(),'Slovak','slk'),
       (134,now(),now(),'Tajik (Tajiki)','tgk'),
       (135,now(),now(),'Isekiri','its'),
       (136,now(),now(),'Ijo lgs.','ijc'),
       (137,now(),now(),'Acehnese','ace'),
       (138,now(),now(),'Kullo','gmo'),
       (139,now(),now(),'Bambara','bam'),
       (140,now(),now(),'Guaraní','grn'),
       (141,now(),now(),'Kikongo','kon'),
       (142,now(),now(),'Norwegian','nob'),
       (143,now(),now(),'Luo','luo'),
       (144,now(),now(),'Sukuma','suk'),
       (145,now(),now(),'Tibetan','bod'),
       (146,now(),now(),'Tsonga','tso'),
       (147,now(),now(),'Lingala','lin'),
       (148,now(),now(),'Kirghiz','kir'),
       (149,now(),now(),'Balinese','ban'),
       (150,now(),now(),'Tashlhiyt (Tachelhit)','shi'),
       (151,now(),now(),'Banjar','bjn'),
       (152,now(),now(),'Bosnian (*)','bos'),
       (153,now(),now(),'Lao (Laotian)','lao'),
       (154,now(),now(),'Bemba (Chibemba)','bem'),
       (155,now(),now(),'Nandi','kln'),
       (156,now(),now(),'Palembang','plm'),
       (157,now(),now(),'Umbundu','umb'),
       (158,now(),now(),'Hazaragi','haz'),
       (159,now(),now(),'Berber','tzm'),
       (160,now(),now(),'Éwé','ewe'),
       (161,now(),now(),'Kamba','kam'),
       (162,now(),now(),'Georgian','kat'),
       (163,now(),now(),'Hebrew (Modern)','heb'),
       (164,now(),now(),'Bangala','bxg'),
       (165,now(),now(),'Luri','lrc'),
       (166,now(),now(),'Shan','shn'),
       (167,now(),now(),'Sotho (Northern)','nso'),
       (168,now(),now(),'Kabyle','kab'),
       (169,now(),now(),'Maninka','emk'),
       (170,now(),now(),'Waray-Waray','war'),
       (171,now(),now(),'Senoufo','seq'),
       (172,now(),now(),'Shekhawati','swv'),
       (173,now(),now(),'Rajbanshi','rjb'),
       (174,now(),now(),'Garhwali','gbm'),
       (175,now(),now(),'Bhili','bhb'),
       (176,now(),now(),'Hindko','hno'),
       (177,now(),now(),'Lithuanian','lit'),
       (178,now(),now(),'Lamani (Lambadi)','lmn'),
       (179,now(),now(),'Low German','nds'),
       (180,now(),now(),'Romani','rmn'),
       (181,now(),now(),'Gilaki','glk'),
       (182,now(),now(),'Bini','bin'),
       (183,now(),now(),'Musi','mui'),
       (184,now(),now(),'Ibibio','ibb'),
       (185,now(),now(),'Dyerma (Zarma)','dje'),
       (186,now(),now(),'Nyankore','nyn'),
       (187,now(),now(),'Beti','btb'),
       (188,now(),now(),'Baule (Baoulé)','bci'),
       (189,now(),now(),'Pu-Xian','cpx'),
       (190,now(),now(),'Kapampangan','pam'),
       (191,now(),now(),'Mazanderani','mzn'),
       (192,now(),now(),'Sidamo','sid'),
       (193,now(),now(),'Brahui','brh'),
       (194,now(),now(),'Tiv','tiv'),
       (195,now(),now(),'Bouyei (Buyi, Giáy)','pcc'),
       (196,now(),now(),'Kumauni','kfy'),
       (197,now(),now(),'Gondi','ggo'),
       (198,now(),now(),'Zande','zne'),
       (199,now(),now(),'Soga','xog'),
       (200,now(),now(),'Ndau','ndc'),
       (201,now(),now(),'Lugbara','lgg'),
       (202,now(),now(),'Galician','glg'),
       (203,now(),now(),'Sadri','sck'),
       (204,now(),now(),'Bagri','bgq'),
       (205,now(),now(),'Ndebele','nbl'),
       (206,now(),now(),'Yao','yao'),
       (207,now(),now(),'Dinka','dip'),
       (208,now(),now(),'Sasak','sas'),
       (209,now(),now(),'Kurux (Kurukh)','kru'),
       (210,now(),now(),'Bedawi (Beja)','bej'),
       (211,now(),now(),'Swati (Swazi)','ssw'),
       (212,now(),now(),'Tulu','tcy'),
       (213,now(),now(),'Waddar','wbq'),
       (214,now(),now(),'Alur','alz'),
       (215,now(),now(),'Slovene (Slovenian)','slv'),
       (216,now(),now(),'Mundani','mnf'),
       (217,now(),now(),'Batak Toba','bbc'),
       (218,now(),now(),'Mundari','muw'),
       (219,now(),now(),'Chiga','cgg'),
       (220,now(),now(),'Kimbundu','kmb'),
       (221,now(),now(),'Gusii','guz'),
       (222,now(),now(),'Meru','mer'),
       (223,now(),now(),'Songe','sop'),
       (224,now(),now(),'Dyula (Jula)','dyu'),
       (225,now(),now(),'Lomwe','ngl'),
       (226,now(),now(),'Mende','men'),
       (227,now(),now(),'Macedonian','mkd'),
       (228,now(),now(),'Teso','teo'),
       (229,now(),now(),'Fongbe (Fon)','fon'),
       (230,now(),now(),'Kangri','xnr'),
       (231,now(),now(),'Tachawit','shy'),
       (232,now(),now(),'Afar','aar'),
       (233,now(),now(),'Wagdi','wbr'),
       (234,now(),now(),'Tarifit','rif'),
       (235,now(),now(),'Sena','seh'),
       (236,now(),now(),'Ngbaka','nga'),
       (237,now(),now(),'Aymara','ayc'),
       (238,now(),now(),'Makonde','kde'),
       (239,now(),now(),'Wolaytta','wal'),
       (240,now(),now(),'Dong','doc'),
       (241,now(),now(),'Pangasinan','pag'),
       (242,now(),now(),'Haya','hay'),
       (243,now(),now(),'Themne (Temne)','tem'),
       (244,now(),now(),'Dimli','diq'),
       (245,now(),now(),'Lango','laj'),
       (246,now(),now(),'Makassar (Makasar)','mak'),
       (247,now(),now(),'Nande','nnb'),
       (248,now(),now(),'Tay','tyz'),
       (249,now(),now(),'Dogri (Dogri-Kangri)','dgo'),
       (250,now(),now(),'Soninke','snk'),
       (251,now(),now(),'Lampung','ljp'),
       (252,now(),now(),'Tigré','tig'),
       (253,now(),now(),'Tumbuka','tum'),
       (254,now(),now(),'Tharu','the'),
       (255,now(),now(),'Khandesi','khn'),
       (256,now(),now(),'Gogo','gog'),
       (257,now(),now(),'Meithei (Meitei)','mni'),
       (258,now(),now(),'Serer-Sine','srr'),
       (259,now(),now(),'Latvian','lav'),
       (260,now(),now(),'Nimadi','noe'),
       (261,now(),now(),'Mandinka','mnk'),
       (262,now(),now(),'Susu','sus'),
       (263,now(),now(),'Tetela','tll'),
       (264,now(),now(),'Tamang','taj'),
       (265,now(),now(),'Nahua (tl)','nhn'),
       (266,now(),now(),'Nyakyusa-Ngonde','nyy'),
       (267,now(),now(),'Occitan','lnc'),
       (268,now(),now(),'Chokwe','cjk'),
       (269,now(),now(),'Teke','ebo'),
       (270,now(),now(),'Tamajaq (Tamasheq)','ttq'),
       (271,now(),now(),'Yaka','yaf'),
       (272,now(),now(),'Igala','igl'),
       (273,now(),now(),'Nuer','nus'),
       (274,now(),now(),'Lendu','led'),
       (275,now(),now(),'Arakanese','mhv'),
       (276,now(),now(),'Acholi','ach'),
       (277,now(),now(),'Masaba','myx'),
       (278,now(),now(),'Hadiyya','hdy'),
       (279,now(),now(),'Tooro','ttj'),
       (280,now(),now(),'Bai','bca'),
       (281,now(),now(),'Hehe','heh'),
       (282,now(),now(),'Shi','shr'),
       (283,now(),now(),'Neo-Aramaic','cld'),
       (284,now(),now(),'Magindanao','mdh'),
       (285,now(),now(),'Chechen','che'),
       (286,now(),now(),'Chuwabu (Chwabo)','chw'),
       (287,now(),now(),'Anaang','anw'),
       (288,now(),now(),'Ha','haq'),
       (289,now(),now(),'Gojri (Gujari)','gju'),
       (290,now(),now(),'Ebira','igb'),
       (291,now(),now(),'Yombe','yom'),
       (292,now(),now(),'Ngambay','sba'),
       (293,now(),now(),'Nyamwezi','nym'),
       (294,now(),now(),'Tonga','toi'),
       (295,now(),now(),'Izon','ijc'),
       (296,now(),now(),'Muong','mtq'),
       (297,now(),now(),'K''iche''','quc'),
       (298,now(),now(),'Malvi','mup'),
       (299,now(),now(),'Batak Dairi','btd'),
       (300,now(),now(),'Batak Simalungun','bts'),
       (301,now(),now(),'Tausug','tsg'),
       (302,now(),now(),'Silt''e','xst'),
       (303,now(),now(),'Chuvash','chv'),
       (304,now(),now(),'Maranao','mrw'),
       (305,now(),now(),'Aja','aja'),
       (306,now(),now(),'Ho','hoc'),
       (307,now(),now(),'Bashkir','bak'),
       (308,now(),now(),'Mewari','mtr'),
       (309,now(),now(),'Kpelle','xpe'),
       (310,now(),now(),'Nupe','nup'),
       (311,now(),now(),'Gbaya (Gbagyi, Gwaya)','gby'),
       (312,now(),now(),'Gourmanchéma (Gurma)','gux'),
       (313,now(),now(),'Mangbetu','mdj'),
       (314,now(),now(),'Songhay','ddn'),
       (315,now(),now(),'Shambala','ksb'),
       (316,now(),now(),'Aimaq','aiq'),
       (317,now(),now(),'Kabardian','kbd'),
       (318,now(),now(),'Anyin','any'),
       (319,now(),now(),'Rejang','rej'),
       (320,now(),now(),'Newari','new'),
       (321,now(),now(),'Venda','ven'),
       (322,now(),now(),'Urhobo','urh'),
       (323,now(),now(),'Luguru','ruf'),
       (324,now(),now(),'Khasi','kha'),
       (325,now(),now(),'Iu Mien','ium'),
       (326,now(),now(),'Qashqa''i','qxq'),
       (327,now(),now(),'Mongo','lol'),
       (328,now(),now(),'Maasai','mas'),
       (329,now(),now(),'Mon','mnw'),
       (330,now(),now(),'Tikar','tik'),
       (331,now(),now(),'Dan','daf'),
       (332,now(),now(),'Mina','myi'),
       (333,now(),now(),'Vasavi','vas'),
       (334,now(),now(),'Bhilali (Bhilala)','bhi'),
       (335,now(),now(),'Jumli','jml'),
       (336,now(),now(),'Karen (Sgaw)','ksw'),
       (337,now(),now(),'Harauti','hoj'),
       (338,now(),now(),'Idoma','idu'),
       (339,now(),now(),'Dagbani','dag'),
       (340,now(),now(),'Kabiyé','kbp'),
       (341,now(),now(),'Comorian','swb'),
       (342,now(),now(),'Estonian','est'),
       (343,now(),now(),'Gã','gaa'),
       (344,now(),now(),'Bena','bez'),
       (345,now(),now(),'Parsi-Dari','prd'),
       (346,now(),now(),'Gorontalo','gor'),
       (347,now(),now(),'Mongondow','mog'),
       (348,now(),now(),'Karen (Pwo)','kjp'),
       (349,now(),now(),'Ikwere','ikw'),
       (350,now(),now(),'Ewondo','ewo'),
       (351,now(),now(),'Nung','nut'),
       (352,now(),now(),'Fur','fvr'),
       (353,now(),now(),'Havu','hav'),
       (354,now(),now(),'Gedeo','drs'),
       (355,now(),now(),'Banda','bjo'),
       (356,now(),now(),'Aringa','luc'),
       (357,now(),now(),'Kwanyama','kua'),
       (358,now(),now(),'Kokborok','trp'),
       (359,now(),now(),'Juray','juy'),
       (360,now(),now(),'Kui','kxu'),
       (361,now(),now(),'Mochi','old'),
       (362,now(),now(),'Nyoro','nyo'),
       (363,now(),now(),'Magar','mgp'),
       (364,now(),now(),'Mandeali','mjl'),
       (365,now(),now(),'Ngaju','nij'),
       (366,now(),now(),'Jingpho','kac'),
       (367,now(),now(),'Ahirani','ahr'),
       (368,now(),now(),'Phende','pem'),
       (369,now(),now(),'Chopi','cce'),
       (370,now(),now(),'Dangme','ada'),
       (371,now(),now(),'Angika (Anga)','anp'),
       (372,now(),now(),'Kefa (Kafa)','kbr'),
       (373,now(),now(),'Garo','grt'),
       (374,now(),now(),'Yucatec (Maya)','yua'),
       (375,now(),now(),'Asu','asa'),
       (376,now(),now(),'Konjo','kjc'),
       (377,now(),now(),'Sardinian','sro'),
       (378,now(),now(),'Efik','efi'),
       (379,now(),now(),'Kinaray-A','krj'),
       (380,now(),now(),'Kisi (Kissi)','kqs'),
       (381,now(),now(),'Lega','lea'),
       (382,now(),now(),'Bari','bfa'),
       (383,now(),now(),'Giryama','nyf'),
       (384,now(),now(),'Dogon','dba'),
       (385,now(),now(),'Wa','wbm'),
       (386,now(),now(),'Batak Angkola','akb'),
       (387,now(),now(),'Nyaturu (Rimi)','rim'),
       (388,now(),now(),'Lozi','loz'),
       (389,now(),now(),'Tai Dam','blt'),
       (390,now(),now(),'Bisa (Bissa)','bib'),
       (391,now(),now(),'Sanga','sng'),
       (392,now(),now(),'Avar','ava'),
       (393,now(),now(),'Bodo','brx'),
       (394,now(),now(),'Malinke','mlq'),
       (395,now(),now(),'Lisu','lis'),
       (396,now(),now(),'K''ekchí','kek'),
       (397,now(),now(),'Manyika','mxc'),
       (398,now(),now(),'Bukusu','bxk'),
       (399,now(),now(),'Komering','kge'),
       (400,now(),now(),'Komo','xom'),
       (401,now(),now(),'Abung','abl'),
       (402,now(),now(),'Nilamba','nim'),
       (403,now(),now(),'Izi-Ezaa-Ikwo-Mgbo','izi'),
       (404,now(),now(),'Tswa','tsc'),
       (405,now(),now(),'Fang','fak'),
       (406,now(),now(),'Yangbye','ybd'),
       (407,now(),now(),'Dai (Hlai)','lic'),
       (408,now(),now(),'Bundeli','bns'),
       (409,now(),now(),'Lü','khb'),
       (410,now(),now(),'Nobiin','fia'),
       (411,now(),now(),'Chakma','ccp'),
       (412,now(),now(),'Kachchi','kfr'),
       (413,now(),now(),'Kanembu','kbl'),
       (414,now(),now(),'Basque','eus'),
       (415,now(),now(),'Maay','ymm'),
       (416,now(),now(),'Ronga','rng'),
       (417,now(),now(),'Bhatri','bgw'),
       (418,now(),now(),'Mwera','mwe'),
       (419,now(),now(),'Baatonum','bba'),
       (420,now(),now(),'Gun','guw'),
       (421,now(),now(),'Ibanag','ibg'),
       (422,now(),now(),'Capiznon (Capiseño)','cps'),
       (423,now(),now(),'Lingao','onb'),
       (424,now(),now(),'Mbandja','zmz'),
       (425,now(),now(),'Ngbandi','nbw'),
       (426,now(),now(),'Karamojong (Karimojong)','kdj'),
       (427,now(),now(),'Karen','NULL'),
       (428,now(),now(),'Sebat Bet Gurage','sgw'),
       (429,now(),now(),'Atuence','atf'),
       (430,now(),now(),'Nsenga','nse'),
       (431,now(),now(),'Diola-Fogny (Jola-Fogny)','dyo'),
       (432,now(),now(),'Kalanga','kck'),
       (433,now(),now(),'Batak Karo','btx'),
       (434,now(),now(),'Maba','mde'),
       (435,now(),now(),'Mizo','lus'),
       (436,now(),now(),'Nyiha','nih'),
       (437,now(),now(),'Waci','wci'),
       (438,now(),now(),'Timorese','aoz'),
       (439,now(),now(),'Yiddish','ydd'),
       (440,now(),now(),'Lahu','lhu'),
       (441,now(),now(),'Mam','mvc'),
       (442,now(),now(),'Friulian (Furlan)','fur'),
       (443,now(),now(),'Ndonga','ndo'),
       (444,now(),now(),'Isoko','iso'),
       (445,now(),now(),'Dazaga','dzg'),
       (446,now(),now(),'Luvale','lue'),
       (447,now(),now(),'Kaqchikel','cak'),
       (448,now(),now(),'Sango','sag'),
       (449,now(),now(),'Fuliiru','flr'),
       (450,now(),now(),'Halbi','hlb'),
       (451,now(),now(),'Kuria','kuj'),
       (452,now(),now(),'Turkana','tuv'),
       (453,now(),now(),'Iraqw','irk'),
       (454,now(),now(),'Adhola','adh'),
       (455,now(),now(),'Dagaare (Dagaari)','dga'),
       (456,now(),now(),'Rhaeto-Romance(Romansch)','roh'),
       (457,now(),now(),'Konkomba','xon'),
       (458,now(),now(),'Aklanon','akl'),
       (459,now(),now(),'Nyambo','now'),
       (460,now(),now(),'Iban','iba'),
       (461,now(),now(),'Lobi','lob'),
       (462,now(),now(),'Phu Thai','pht'),
       (463,now(),now(),'Hani','hni'),
       (464,now(),now(),'Khmu''','kjg'),
       (465,now(),now(),'Tetun','tet'),
       (466,now(),now(),'Mahasu Pahari','bfz'),
       (467,now(),now(),'Embu (Embo)','ebu'),
       (468,now(),now(),'Bété','bev'),
       (469,now(),now(),'Lezgian (Lezgi)','lez'),
       (470,now(),now(),'Dayak (Malayic D.)','xdy'),
       (471,now(),now(),'Korku','kfq'),
       (472,now(),now(),'Bemba (Kinyabemba)','bmy'),
       (473,now(),now(),'Adyghe','ady'),
       (474,now(),now(),'Ossetic (Osetin)','oss'),
       (475,now(),now(),'Shina','scl'),
       (476,now(),now(),'Welsh','cym'),
       (477,now(),now(),'Karakalpak','kaa'),
       (478,now(),now(),'Koli','gjk'),
       (479,now(),now(),'Bima','bhp'),
       (480,now(),now(),'Manggarai','mqy'),
       (481,now(),now(),'Tai Dón','twh'),
       (482,now(),now(),'Tengger','tes'),
       (483,now(),now(),'Toraja (Toraja-Sa''dan)','sda'),
       (484,now(),now(),'Maltese','mlt'),
       (485,now(),now(),'Tshangla','tsj'),
       (486,now(),now(),'Awngi','awn'),
       (487,now(),now(),'Masbatenyo','msb'),
       (488,now(),now(),'Makhuwa-Meetto','mgh'),
       (489,now(),now(),'Tabwa (Taabwa)','tap'),
       (490,now(),now(),'Attié','ati'),
       (491,now(),now(),'Osing','osi'),
       (492,now(),now(),'Bembe','bmb'),
       (493,now(),now(),'Gwere','gwr'),
       (494,now(),now(),'Karbi','mjw'),
       (495,now(),now(),'Nias','nia'),
       (496,now(),now(),'Parauk','prk'),
       (497,now(),now(),'Zigula','ziw'),
       (498,now(),now(),'Langi','lag'),
       (499,now(),now(),'Bassa','bsq'),
       (500,now(),now(),'Angas (Ngas)','anc'),
       (501,now(),now(),'Mumuye','mzm'),
       (502,now(),now(),'Kayah Li (E)','eky'),
       (503,now(),now(),'Surigaonon','sul'),
       (504,now(),now(),'Limba','lia'),
       (505,now(),now(),'Bozo','boz'),
       (506,now(),now(),'Fijian','fij'),
       (507,now(),now(),'Dagara','dgi'),
       (508,now(),now(),'Wè (Wobe)','wob'),
       (509,now(),now(),'Gurenne','gur'),
       (510,now(),now(),'Oirat','xal'),
       (511,now(),now(),'Varli','vav'),
       (512,now(),now(),'Dargwa','dar'),
       (513,now(),now(),'Bobo Madaré (Bobo Fing)','bbo'),
       (514,now(),now(),'Akha','ahk'),
       (515,now(),now(),'Bantawa','bap'),
       (516,now(),now(),'Zapotec','zai'),
       (517,now(),now(),'Bwa (Bwamu)','bww'),
       (518,now(),now(),'Kusaal','kus'),
       (519,now(),now(),'Kuy','kdt'),
       (520,now(),now(),'Buriat','bxm'),
       (521,now(),now(),'Mising (Miri)','mrg'),
       (522,now(),now(),'Budza','bja'),
       (523,now(),now(),'Wadiyara Koli','kxp'),
       (524,now(),now(),'Dzongkha','dzo'),
       (525,now(),now(),'Mari (Cheremis)','mrj'),
       (526,now(),now(),'Bagheli','bfy'),
       (527,now(),now(),'Frisian','fri'),
       (528,now(),now(),'Kenyi','lke'),
       (529,now(),now(),'Samoan','smo'),
       (530,now(),now(),'Masalit','mls'),
       (531,now(),now(),'Pa''o Karen','blk'),
       (532,now(),now(),'Chaga (Chagga)','jmc'),
       (533,now(),now(),'Pökoot (Pokot)','pko'),
       (534,now(),now(),'Vunjo','vun'),
       (535,now(),now(),'Daju','daj'),
       (536,now(),now(),'Batak Mandailing','btm'),
       (537,now(),now(),'Guro','goa'),
       (538,now(),now(),'Pesisir','pec'),
       (539,now(),now(),'Pubian','pun'),
       (540,now(),now(),'Limbu','lif'),
       (541,now(),now(),'Gen','gej'),
       (542,now(),now(),'Ruund','rnd'),
       (543,now(),now(),'Kenuzi(Kunuz, Dongolese)','kzh'),
       (544,now(),now(),'Ndo','ndp'),
       (545,now(),now(),'Udmurt','udm'),
       (546,now(),now(),'Fiji Hindustani','hif'),
       (547,now(),now(),'Naba','mne'),
       (548,now(),now(),'Inor','ior'),
       (549,now(),now(),'Pashayi','aee'),
       (550,now(),now(),'Anyin Morofo','mtb'),
       (551,now(),now(),'Ede Nago','nqg'),
       (552,now(),now(),'Digo','dig'),
       (553,now(),now(),'Grebo','gry'),
       (554,now(),now(),'Balanta-Kentohe','ble'),
       (555,now(),now(),'Ngando','ngd'),
       (556,now(),now(),'Ngoni','ngo'),
       (557,now(),now(),'Kanyok','kny'),
       (558,now(),now(),'Luxembourgeois','ltz'),
       (559,now(),now(),'Kim Mun','mji'),
       (560,now(),now(),'Fipa','fip'),
       (561,now(),now(),'Idakho-Isukha-Tiriki','ida'),
       (562,now(),now(),'Nyole','nuj'),
       (563,now(),now(),'Yakut','sah'),
       (564,now(),now(),'Pengo','peg'),
       (565,now(),now(),'Kumyk','kum'),
       (566,now(),now(),'Tem','kdh'),
       (567,now(),now(),'Yemba','ybb'),
       (568,now(),now(),'Mordvin (Erzya)','myv'),
       (569,now(),now(),'Ghomálá'' (Bamendjuu)','bbj'),
       (570,now(),now(),'Mambwe-Lungu','mgr'),
       (571,now(),now(),'Tamajeq','tmh'),
       (572,now(),now(),'Gurung','ggn'),
       (573,now(),now(),'Logo','log'),
       (574,now(),now(),'Ingush','inh'),
       (575,now(),now(),'Tarok','yer'),
       (576,now(),now(),'Domari','rmt'),
       (577,now(),now(),'Bareli','bfb'),
       (578,now(),now(),'Tai Nüa','tdd'),
       (579,now(),now(),'Berom (Birom)','bom'),
       (580,now(),now(),'Jju','kaj'),
       (581,now(),now(),'Kamwe','hig'),
       (582,now(),now(),'Soddo','gru'),
       (583,now(),now(),'Koya','kff'),
       (584,now(),now(),'Cham','cjm'),
       (585,now(),now(),'Mingrelian','xmf'),
       (586,now(),now(),'Mwaghavul (Mupun)','sur'),
       (587,now(),now(),'Jarai','jra'),
       (588,now(),now(),'Crimean Turkish (Crimean Tatar)','crh'),
       (589,now(),now(),'Hunde','hke'),
       (590,now(),now(),'Lunda','lun'),
       (591,now(),now(),'Mbala','mdp'),
       (592,now(),now(),'Budu','buu'),
       (593,now(),now(),'Gaelic, Irish','gle'),
       (594,now(),now(),'Kaonde','kqn'),
       (595,now(),now(),'Kulango','kzc'),
       (596,now(),now(),'Koranko (Kuranko)','knk'),
       (597,now(),now(),'Nzema','nzi'),
       (598,now(),now(),'Tavoyan','tvn'),
       (599,now(),now(),'Breton','bre'),
       (600,now(),now(),'Ma''di','mhi'),
       (601,now(),now(),'Mundang','mua'),
       (602,now(),now(),'Ayizo','ayb'),
       (603,now(),now(),'Zaghawa','zag'),
       (604,now(),now(),'Mann (Mano)','mev'),
       (605,now(),now(),'Palaung','pce'),
       (606,now(),now(),'Saurashtra','saz'),
       (607,now(),now(),'Dhivehi','div'),
       (608,now(),now(),'Masa (Masana)','mcn'),
       (609,now(),now(),'Musey','mse'),
       (610,now(),now(),'Etsako','ets'),
       (611,now(),now(),'Basaá','bas'),
       (612,now(),now(),'Naxi','nbf'),
       (613,now(),now(),'Yerukula','yeu'),
       (614,now(),now(),'Tupuri','tui'),
       (615,now(),now(),'Mpuono','zmp'),
       (616,now(),now(),'Bilaspuri','kfs'),
       (617,now(),now(),'Hemba','hem'),
       (618,now(),now(),'Talysh (Talishi)','tly'),
       (619,now(),now(),'Waxianghua','wxa'),
       (620,now(),now(),'Lala-Bisa','leb'),
       (621,now(),now(),'Marka','rkm'),
       (622,now(),now(),'Samo','sbd'),
       (623,now(),now(),'Sora','srb'),
       (624,now(),now(),'Ndali','ndh'),
       (625,now(),now(),'Kalabari','ijn'),
       (626,now(),now(),'Sumbawa','smw'),
       (627,now(),now(),'Duruma','dug'),
       (628,now(),now(),'Bamun','bax'),
       (629,now(),now(),'Goajiro (Guajiro)','guc'),
       (630,now(),now(),'Icelandic','isl'),
       (631,now(),now(),'Kankanay','kne'),
       (632,now(),now(),'Ngindo','nnq'),
       (633,now(),now(),'Kharia','khr'),
       (634,now(),now(),'Bangubangu','bnx'),
       (635,now(),now(),'Bunu','bwx'),
       (636,now(),now(),'Bade','bde'),
       (637,now(),now(),'Mapudungun','arn'),
       (638,now(),now(),'Sama','sse'),
       (639,now(),now(),'Bura-Pabir','bwr'),
       (640,now(),now(),'Jita','jit'),
       (641,now(),now(),'Kagulu (Kaguru)','kki'),
       (642,now(),now(),'Wasa','wss'),
       (643,now(),now(),'Kasem','xsm'),
       (644,now(),now(),'Kirike','okr'),
       (645,now(),now(),'Tzotzil','tzc'),
       (646,now(),now(),'Kaili','lew'),
       (647,now(),now(),'Lewotobi','lwt'),
       (648,now(),now(),'Panchpargania','tdb'),
       (649,now(),now(),'Surajpuri','sjp'),
       (650,now(),now(),'Sar','mwm'),
       (651,now(),now(),'Shilluk','shk'),
       (652,now(),now(),'Gamit','gbl'),
       (653,now(),now(),'Seba','kdg'),
       (654,now(),now(),'Otomí','otz'),
       (655,now(),now(),'Binji','bpj'),
       (656,now(),now(),'Balti','bft'),
       (657,now(),now(),'Tolaki','lbw'),
       (658,now(),now(),'Rade','rad'),
       (659,now(),now(),'Tzeltal','tzb'),
       (660,now(),now(),'Ekpeye','ekp'),
       (661,now(),now(),'Taita','dav'),
       (662,now(),now(),'Kele','khy'),
       (663,now(),now(),'Karachay-Balkar','krc'),
       (664,now(),now(),'Nama','naq'),
       (665,now(),now(),'Birifor','bfo'),
       (666,now(),now(),'Rufiji','rui'),
       (667,now(),now(),'Dani','dni'),
       (668,now(),now(),'Kerinci','kvr'),
       (669,now(),now(),'Manza','mzv'),
       (670,now(),now(),'Manjaku (Mandjak)','mfv'),
       (671,now(),now(),'Bushoong','buf'),
       (672,now(),now(),'Ding','diz'),
       (673,now(),now(),'Manobo','mbb'),
       (674,now(),now(),'Sangir','sxn'),
       (675,now(),now(),'Medumba','byv'),
       (676,now(),now(),'Koromfé','kfz'),
       (677,now(),now(),'Moba','mfq'),
       (678,now(),now(),'Badaga','bfq'),
       (679,now(),now(),'Nyungwe','nyu'),
       (680,now(),now(),'Maria','mrr'),
       (681,now(),now(),'Ngombe','ngc'),
       (682,now(),now(),'Sumbwa','suw'),
       (683,now(),now(),'Dongxiang (Santa)','sce'),
       (684,now(),now(),'Nyanga','nyj'),
       (685,now(),now(),'Tembo','tbt'),
       (686,now(),now(),'Gulay','gvl'),
       (687,now(),now(),'Nuni','nuv'),
       (688,now(),now(),'Kokota','kkk'),
       (689,now(),now(),'Nishi (Nisi)','dap'),
       (690,now(),now(),'Tae''','rob'),
       (691,now(),now(),'Tukang Besi','bhq'),
       (692,now(),now(),'Nyamwanga','mwn'),
       (693,now(),now(),'Pogoro','poy'),
       (694,now(),now(),'Tuvan (Tuvinian)','tyv'),
       (695,now(),now(),'Klao','klu'),
       (696,now(),now(),'Tewe','twx'),
       (697,now(),now(),'Bokyi','bky'),
       (698,now(),now(),'Adi','adi'),
       (699,now(),now(),'Enga','enq'),
       (700,now(),now(),'Kono','kno'),
       (701,now(),now(),'Brunei','kxd'),
       (702,now(),now(),'Dubla (Dubli)','dub'),
       (703,now(),now(),'Bench (Ghimarra)','bcq'),
       (704,now(),now(),'Chodri','cdi'),
       (705,now(),now(),'Khowar','khw'),
       (706,now(),now(),'Logooli','rag'),
       (707,now(),now(),'Saho','ssy'),
       (708,now(),now(),'Lyélé','lee'),
       (709,now(),now(),'Sehwi','sfw'),
       (710,now(),now(),'Aushi','auh'),
       (711,now(),now(),'Caluyanun','clu'),
       (712,now(),now(),'Kambera','xbr'),
       (713,now(),now(),'Kurumba','kfi'),
       (714,now(),now(),'Ekit','eke'),
       (715,now(),now(),'Gera','gew'),
       (716,now(),now(),'Goemai','ank'),
       (717,now(),now(),'Hmong Daw','mww'),
       (718,now(),now(),'Kana (Khana)','ogo'),
       (719,now(),now(),'Obolo','ann'),
       (720,now(),now(),'Ogbia','ogb'),
       (721,now(),now(),'Bulu','bum'),
       (722,now(),now(),'Totonac','tlc'),
       (723,now(),now(),'Dusun','dun'),
       (724,now(),now(),'Gumuz','guk'),
       (725,now(),now(),'Kohumono','bcs'),
       (726,now(),now(),'Bera (Kibira)','brf'),
       (727,now(),now(),'Phuan','phu'),
       (728,now(),now(),'Corsican','cos'),
       (729,now(),now(),'Aromunian','rup'),
       (730,now(),now(),'Muna','mnb'),
       (731,now(),now(),'Kohistani','plk'),
       (732,now(),now(),'Basa (Abacha)','bzw'),
       (733,now(),now(),'Gonja','gjn'),
       (734,now(),now(),'Tonga','tog'),
       (735,now(),now(),'Kuvi','kxv'),
       (736,now(),now(),'Tonga','toh'),
       (737,now(),now(),'Mauka (Mahou)','mxx'),
       (738,now(),now(),'Otuho','lot'),
       (739,now(),now(),'Bomu (Boomu)','bmq'),
       (740,now(),now(),'Hema','nix'),
       (741,now(),now(),'Kom','bkm'),
       (742,now(),now(),'Romblomanon','rol'),
       (743,now(),now(),'Mampruli','maw'),
       (744,now(),now(),'Safwa','sbk'),
       (745,now(),now(),'Hmong Njua','blu'),
       (746,now(),now(),'Kakwa','keo'),
       (747,now(),now(),'Punu','buh'),
       (748,now(),now(),'Kado','kdv'),
       (749,now(),now(),'Lama','las'),
       (750,now(),now(),'Berta','wti'),
       (751,now(),now(),'Mbunda','mck'),
       (752,now(),now(),'Ifè','ife'),
       (753,now(),now(),'Kadara','kad'),
       (754,now(),now(),'Lucazi (Luchazi)','lch'),
       (755,now(),now(),'Mazatec(o)','maq'),
       (756,now(),now(),'Ifugao','ifb'),
       (757,now(),now(),'Mafa','maf'),
       (758,now(),now(),'Shubi','suj'),
       (759,now(),now(),'Toma','tod'),
       (760,now(),now(),'Yakan','yka'),
       (761,now(),now(),'Zimba','zmb'),
       (762,now(),now(),'Huba','hbb'),
       (763,now(),now(),'Karekare','kai'),
       (764,now(),now(),'Nawdm','nmz'),
       (765,now(),now(),'Sui','swi'),
       (766,now(),now(),'Hangaza','han'),
       (767,now(),now(),'Suba','suh'),
       (768,now(),now(),'Loma','lom'),
       (769,now(),now(),'Mandar','mdr'),
       (770,now(),now(),'Ogbah','ogc'),
       (771,now(),now(),'Nkhumbi','khu'),
       (772,now(),now(),'Subanen','laa'),
       (773,now(),now(),'Xamtanga','xan'),
       (774,now(),now(),'Mbere','mdt'),
       (775,now(),now(),'Ntcham','bud'),
       (776,now(),now(),'Komi-Zyrian','kpv'),
       (777,now(),now(),'Sebei','kpz'),
       (778,now(),now(),'Lamba','lam'),
       (779,now(),now(),'Cao Lan','mlc'),
       (780,now(),now(),'Kumam','kdi'),
       (781,now(),now(),'Marba','mpg'),
       (782,now(),now(),'Melpa','med'),
       (783,now(),now(),'Kposo','kpo'),
       (784,now(),now(),'Mandari','mqu'),
       (785,now(),now(),'Itawis (Itawit)','itv'),
       (786,now(),now(),'Mambae','mgm'),
       (787,now(),now(),'Ilanun','mbi'),
       (788,now(),now(),'Kinga','gmx'),
       (789,now(),now(),'Dida','dic'),
       (790,now(),now(),'Lokaa','yaz'),
       (791,now(),now(),'Mbembe','mfn'),
       (792,now(),now(),'Ntomba','nto'),
       (793,now(),now(),'Mordvin (Moksha)','mdf'),
       (794,now(),now(),'Zinza','zin'),
       (795,now(),now(),'Sadri, Oraon','sdr'),
       (796,now(),now(),'Gagauz','gag'),
       (797,now(),now(),'Sô','teu'),
       (798,now(),now(),'Gayo','gay'),
       (799,now(),now(),'Blaan (Bolinao)','bpr'),
       (800,now(),now(),'Jur Mödö','bex'),
       (801,now(),now(),'Ngulu','ngp'),
       (802,now(),now(),'Navajo','nav'),
       (803,now(),now(),'Nyaneka','nyk'),
       (804,now(),now(),'Sherbro','bun'),
       (805,now(),now(),'Bacama','bcy'),
       (806,now(),now(),'Bata','bta'),
       (807,now(),now(),'Jarawa','jar'),
       (808,now(),now(),'Tsuvadi','tvd'),
       (809,now(),now(),'Alaba','alw'),
       (810,now(),now(),'Tugen','tuy'),
       (811,now(),now(),'Sabaot','spy'),
       (812,now(),now(),'Sika (Sikka)','ski'),
       (813,now(),now(),'Bahnar','bdq'),
       (814,now(),now(),'Fe''fe''','fmp'),
       (815,now(),now(),'Bolia','bli'),
       (816,now(),now(),'Ditammari','tbz'),
       (817,now(),now(),'Lengola','lej'),
       (818,now(),now(),'Mayogo','mdm'),
       (819,now(),now(),'Ngiti','niy'),
       (820,now(),now(),'Tongan','ton'),
       (821,now(),now(),'Yansi','yns'),
       (822,now(),now(),'Samburu','saq'),
       (823,now(),now(),'Tai Daeng','tyr'),
       (824,now(),now(),'Gor','gqr'),
       (825,now(),now(),'Nyemba','nba'),
       (826,now(),now(),'Parsi','prp'),
       (827,now(),now(),'Bru','bru'),
       (828,now(),now(),'Cuyonon','cyo'),
       (829,now(),now(),'Herero','her'),
       (830,now(),now(),'Lamnso''','lns'),
       (831,now(),now(),'Dhatki','mki'),
       (832,now(),now(),'Didinga','did'),
       (833,now(),now(),'Toposa','toq'),
       (834,now(),now(),'Eggon','ego'),
       (835,now(),now(),'Sisaala','ssl'),
       (836,now(),now(),'Sonde','shc'),
       (837,now(),now(),'Xasonga','kao'),
       (838,now(),now(),'Gaelic, Scots','gla'),
       (839,now(),now(),'Bantoanon','bno'),
       (840,now(),now(),'Mambila','mcu'),
       (841,now(),now(),'Wali','wlx'),
       (842,now(),now(),'Kunama','kun'),
       (843,now(),now(),'Chol','cti'),
       (844,now(),now(),'Marghi (Margi)','mrt'),
       (845,now(),now(),'Garreh-Ajuran','ggh'),
       (846,now(),now(),'Jalonke (Yalunka)','yal'),
       (847,now(),now(),'Mangghuer (Tu)','mjg'),
       (848,now(),now(),'Mango','mge'),
       (849,now(),now(),'Loko','lok'),
       (850,now(),now(),'Sherpa','xsr'),
       (851,now(),now(),'Tai Hongjin','tiz'),
       (852,now(),now(),'Wojenaka','jod'),
       (853,now(),now(),'Tangale','tan'),
       (854,now(),now(),'Gworok','kcg'),
       (855,now(),now(),'Anufo','cko'),
       (856,now(),now(),'Kendayan','knx'),
       (857,now(),now(),'Lamaholot','slp'),
       (858,now(),now(),'Ma''anyan','mhy'),
       (859,now(),now(),'Tontemboan','tnt'),
       (860,now(),now(),'Dendi','ddn'),
       (861,now(),now(),'Lolo','llb'),
       (862,now(),now(),'Manyawa','mny'),
       (863,now(),now(),'Mbwela','mfu'),
       (864,now(),now(),'Ndengereko','ndg'),
       (865,now(),now(),'Takwane','tke'),
       (866,now(),now(),'Mehri','gdq'),
       (867,now(),now(),'Saya','say'),
       (868,now(),now(),'Chonyi','coh'),
       (869,now(),now(),'Huastec','hsf'),
       (870,now(),now(),'Lak','lbe'),
       (871,now(),now(),'Nyore','nyd'),
       (872,now(),now(),'Anuak (Anywak)','anu'),
       (873,now(),now(),'Bajau','bdl'),
       (874,now(),now(),'Koyra (Koorete)','kqy'),
       (875,now(),now(),'Kunda','kdn'),
       (876,now(),now(),'Lenje','leh'),
       (877,now(),now(),'Awutu','afu'),
       (878,now(),now(),'Duala','dua'),
       (879,now(),now(),'Qiang','cng'),
       (880,now(),now(),'Ruli','ruc'),
       (881,now(),now(),'Saafi-Saafi','sav'),
       (882,now(),now(),'Esan','ish'),
       (883,now(),now(),'Gola','gol'),
       (884,now(),now(),'Buli','bwu'),
       (885,now(),now(),'Kwaya','kya'),
       (886,now(),now(),'Provençal','prv'),
       (887,now(),now(),'Tharaka','thk'),
       (888,now(),now(),'Makasae','mkz'),
       (889,now(),now(),'Mbay','myb'),
       (890,now(),now(),'Ngbaka Ma''bo','nbm'),
       (891,now(),now(),'Bakundu','bdu'),
       (892,now(),now(),'Ahanta','aha'),
       (893,now(),now(),'Akoose','bss'),
       (894,now(),now(),'Binukid','bkd'),
       (895,now(),now(),'Davawenyo','daw'),
       (896,now(),now(),'Kerewe (Kerebe)','ked'),
       (897,now(),now(),'Ndendeule','dne'),
       (898,now(),now(),'Ron','cla'),
       (899,now(),now(),'Talinga-Bwisi','tlj'),
       (900,now(),now(),'Garífuna','cab'),
       (901,now(),now(),'Kako','kkj'),
       (902,now(),now(),'Nafusi','jbn'),
       (903,now(),now(),'Vai','vai'),
       (904,now(),now(),'Bitare','brt'),
       (905,now(),now(),'Kare','kbn'),
       (906,now(),now(),'Katcha-Kadugli-Miri','xtc'),
       (907,now(),now(),'Koho','kpm'),
       (908,now(),now(),'Kwere','cwe'),
       (909,now(),now(),'Ngiemboon (Ngyemboon)','nnh'),
       (910,now(),now(),'Amis','ami'),
       (911,now(),now(),'Li''o','ljl'),
       (912,now(),now(),'Maxi','mxl'),
       (913,now(),now(),'Ngäbere','gym'),
       (914,now(),now(),'Chinantec','cco'),
       (915,now(),now(),'Kono','knu'),
       (916,now(),now(),'Luwo','lwo'),
       (917,now(),now(),'Mazahua','maz'),
       (918,now(),now(),'Kofyar','kwl'),
       (919,now(),now(),'Pangwa','pbr'),
       (920,now(),now(),'Sakata','skt'),
       (921,now(),now(),'Kewa','kew'),
       (922,now(),now(),'Purik (Purki)','prx'),
       (923,now(),now(),'Samba Daka','ccg'),
       (924,now(),now(),'Kangean','kkv'),
       (925,now(),now(),'Musgu','mug'),
       (926,now(),now(),'Lele','lln'),
       (927,now(),now(),'Meta''','mgo'),
       (928,now(),now(),'Mom Jango','ver'),
       (929,now(),now(),'Rwa','rwk'),
       (930,now(),now(),'Adioukrou','adj'),
       (931,now(),now(),'Kataang','kgd'),
       (932,now(),now(),'Khengkha','xkf'),
       (933,now(),now(),'Bandi','bza'),
       (934,now(),now(),'Datooga','tcc'),
       (935,now(),now(),'Kuman','kue'),
       (936,now(),now(),'Nancere','nnc'),
       (937,now(),now(),'Pana','pnz'),
       (938,now(),now(),'Abron','abr'),
       (939,now(),now(),'Kemak','kem'),
       (940,now(),now(),'Mada','mda'),
       (941,now(),now(),'Purépecha','tsz'),
       (942,now(),now(),'Sedang','sed'),
       (943,now(),now(),'Bekwarra','bkv'),
       (944,now(),now(),'Bole','bol'),
       (945,now(),now(),'Che','ruk'),
       (946,now(),now(),'Cibak','ckl'),
       (947,now(),now(),'Cishingini','asg'),
       (948,now(),now(),'Dibo','dio'),
       (949,now(),now(),'Emai-Iuleha-Ora','ema'),
       (950,now(),now(),'Gokana','gkn'),
       (951,now(),now(),'Hre','hre'),
       (952,now(),now(),'Hyam','jab'),
       (953,now(),now(),'Kara','reg'),
       (954,now(),now(),'Mískito','miq'),
       (955,now(),now(),'Moru','mgd'),
       (956,now(),now(),'Tera','ttr'),
       (957,now(),now(),'Tsikimba','kdl'),
       (958,now(),now(),'Tsishingini','tsw'),
       (959,now(),now(),'Bunak','bfn'),
       (960,now(),now(),'Mro Chin','cmr'),
       (961,now(),now(),'Tabassaran','tab'),
       (962,now(),now(),'Bilin (Bilen)','byn'),
       (963,now(),now(),'Bimoba','bim'),
       (964,now(),now(),'Wéménugbé (Weme)','wem'),
       (965,now(),now(),'Ama (Nyima, Nyimang)','nyi'),
       (966,now(),now(),'Giziga','gis'),
       (967,now(),now(),'Yemsa','jnj'),
       (968,now(),now(),'Kiribati','gil'),
       (969,now(),now(),'Sabu (Sawu)','hvn'),
       (970,now(),now(),'Bena (Yungur)','yun'),
       (971,now(),now(),'Kalagan','kqe'),
       (972,now(),now(),'Kukele','kez'),
       (973,now(),now(),'Sizaki','szk'),
       (974,now(),now(),'Tippera','tpe'),
       (975,now(),now(),'Mpoto','mpa'),
       (976,now(),now(),'Ingessana (Gaam)','tbi'),
       (977,now(),now(),'Lambya','lai'),
       (978,now(),now(),'Zaiwa','atb'),
       (979,now(),now(),'Ende','end'),
       (980,now(),now(),'Makaa','mcp'),
       (981,now(),now(),'Pamona','bcx'),
       (982,now(),now(),'Sagala','sbm'),
       (983,now(),now(),'Tondano','tdn'),
       (984,now(),now(),'C''lela (Lela)','dri'),
       (985,now(),now(),'Kadazan','kzj'),
       (986,now(),now(),'Kimbu','kiv'),
       (987,now(),now(),'Huli','hul'),
       (988,now(),now(),'Balanta-Ganja','bjt'),
       (989,now(),now(),'Inonhan','loc'),
       (990,now(),now(),'Kamayo','kyk'),
       (991,now(),now(),'Nara','nrb'),
       (992,now(),now(),'Selako','skl'),
       (993,now(),now(),'Biyo','byo'),
       (994,now(),now(),'Honi','how'),
       (995,now(),now(),'Koyaga','kga'),
       (996,now(),now(),'Kwese','kws'),
       (997,now(),now(),'Limbum','lmp'),
       (998,now(),now(),'Lobala','loq'),
       (999,now(),now(),'Mamvu','mdi'),
       (1000,now(),now(),'Papel','pbo'),
       (1001,now(),now(),'Salampasu','slx'),
       (1002,now(),now(),'Worodougou','jud'),
       (1003,now(),now(),'Chaungtha','ccq'),
       (1004,now(),now(),'Jadgali','jdg'),
       (1005,now(),now(),'Khün','kkh'),
       (1006,now(),now(),'Sangu','sbp'),
       (1007,now(),now(),'Tahitian','tah'),
       (1008,now(),now(),'Kanjobal','kjb'),
       (1009,now(),now(),'Bakumpai','bkr'),
       (1010,now(),now(),'Banggai','bgz'),
       (1011,now(),now(),'Ede Idaca','idd'),
       (1012,now(),now(),'Ekari','ekg'),
       (1013,now(),now(),'Lawangan','lbx'),
       (1014,now(),now(),'Mamasa','mqj'),
       (1015,now(),now(),'Simeulue','smr'),
       (1016,now(),now(),'Dagur','dta'),
       (1017,now(),now(),'Gidar','gid'),
       (1018,now(),now(),'Murle','mur'),
       (1019,now(),now(),'Subanon','skn'),
       (1020,now(),now(),'Ebrié','ebr'),
       (1021,now(),now(),'Ngwe','nwe'),
       (1022,now(),now(),'Talaud','tld'),
       (1023,now(),now(),'Bumthangkha','kjz'),
       (1024,now(),now(),'Endo','enb'),
       (1025,now(),now(),'Matuumbi','mgw'),
       (1026,now(),now(),'Tlapanec','tpx'),
       (1027,now(),now(),'Waneci','wne');